[project]
name = "urlclean"
version = "0.4.6"
description = "Simple url cleaning script"
requires-python = "==3.13.*"
dependencies = [
    "clipman>=3.3.3",
    "cx-freeze>=8.6.4",
    "icecream>=2.2.0",
    "requests>=2.34.2",
    "typer>=0.24.1",
    "yarl==1.24.5",
]

[[tool.cxfreeze.executables]]
script = "main.py"
base = "console"
copyright = "Copyright (C) 2025 yukiyosanako"
target_name = "urlclean"
#shortcut_name = "urlclean"
#shortcut_dir = "MyProgramMenu"

[tool.cxfreeze.build_exe]
zip_include_packages = []
optimize = 2
