name: Pre Release

on:
  push:
    branches:
      - "dev/**"
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE*"
      - ".github/workflows/dependabot-auto-merge.yml"

permissions:
  contents: write

jobs:
  build:
    uses: T2PeNBiX99wcoxKv3A4g/Release-Workflows/.github/workflows/python_uv_release.yml@main
    with:
      filename: URLClean